import {
  AccessGrant,
  AdapterMode,
  AppState,
  AuthMechanism,
  BrokerUser,
  Carrier,
  KnowledgeDoc,
  TrustTier,
  AccessRole,
} from './models.js';

function uid(prefix = 'id'): string {
  return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

const seedTime = new Date().toISOString();

const pilotCarriers: Carrier[] = [
  {
    id: 'carrier-cna',
    name: 'CNA',
    adapterMode: 'PORTAL_GUIDED' as AdapterMode,
    supportsApi: false,
    requiresMfa: true,
    mfaMethod: 'totp',
    loginHint: 'cna-user',
    timeoutHours: 4,
    defaultTrustTier: 'TIER_2_CACHED_SESSION' as TrustTier,
    portalUrl: 'https://www.cna.com/agentcenterpublic',
    authMechanism: 'credentials' as AuthMechanism,
    notes: 'Common with high portal variance; starts with guided broker workflow.',
  },
  {
    id: 'carrier-hartford',
    name: 'The Hartford',
    adapterMode: 'API_FEDERATED' as AdapterMode,
    supportsApi: true,
    requiresMfa: true,
    mfaMethod: 'push',
    loginHint: 'portal-hartford',
    timeoutHours: 2,
    defaultTrustTier: 'TIER_2_CACHED_SESSION' as TrustTier,
    portalUrl: 'https://global.thehartford.com/s/login/ForgotPassword',
    authMechanism: 'sso_redirect' as AuthMechanism,
    notes: 'Preferred integration target for durable path.',
  },
  {
    id: 'carrier-travelers',
    name: 'Travelers',
    adapterMode: 'API_FEDERATED' as AdapterMode,
    supportsApi: true,
    requiresMfa: true,
    mfaMethod: 'email',
    loginHint: 'travellers-admin',
    timeoutHours: 3,
    defaultTrustTier: 'TIER_3_STORED_REGISTRY' as TrustTier,
    portalUrl: 'https://signin.travelers.com/',
    authMechanism: 'email_code' as AuthMechanism,
    notes: 'Often supports role mapping via API where available.',
  },
  {
    id: 'carrier-monoline',
    name: 'Monoline Work Comp',
    adapterMode: 'PORTAL_GUIDED' as AdapterMode,
    supportsApi: false,
    requiresMfa: true,
    mfaMethod: 'sms',
    loginHint: 'workcomp-prod',
    timeoutHours: 8,
    defaultTrustTier: 'TIER_1_ENTER_EVERY_TIME' as TrustTier,
    portalUrl: 'https://www.argogroup.com/agent-login/',
    authMechanism: 'credentials' as AuthMechanism,
    notes: 'High-friction carrier; usually needs guided sign-in today.',
  },
  {
    id: 'carrier-aman',
    name: 'AMN (AFLAC)',
    adapterMode: 'EMAIL_FORM' as AdapterMode,
    supportsApi: false,
    requiresMfa: false,
    mfaMethod: 'totp',
    loginHint: 'amnaf-user',
    timeoutHours: 12,
    defaultTrustTier: 'TIER_1_ENTER_EVERY_TIME' as TrustTier,
    portalUrl:
      'https://argolimited.okta.com/oauth2/default/v1/authorize?client_id=0oa124mlqcdQYay9F2p8&redirect_uri=https%3A%2F%2Fagentportal.argolimited.com%2Findex.aspx&response_type=code&scope=openid%20profile%20email&code_challenge=e1pbEnltW82S9frTrplHoL0-8qOe67HSYzOca-2oM5U&code_challenge_method=S256&state=OpenIdConnect.AuthenticationProperties%3DSfS5JXEKO2KT_VrMwKMxVssbNtzhk7JcwhuxYPrkVTFYhpQFnQ4n6OvBOL_kaWSufabbDa_ZbrQFCCc5JIpVDoJQu3YLWN4To-lilicg3n5ZQInRjYFIBn7JlkSLYiMonZwwQmBmvVh4lCNHDYZkn7N-KXNM15JehLeKi8DnCG_d5QPSZREtNmUHKp44qv1oVPPTZ9I7Izt-ZGVIFBCNQTin2ElKF8cbcl8xhrj-7219FSPheud4-xF7MWTHHBhQOI---YQaSxovcH2VKVKu3-UEHYHp4gExnVHWfocuofWrnp8JnKnCdB9-riqNO_FNTBcuZKsJvrLE7LaCKq9Uiw&response_mode=form_post&nonce=639174380612924319.NTgyMDIyYTktZWM2Zi00MDczLTlhNTgtM2VkZTM5NTQzZjNmNjg5ZWM3Y2ItNDRkZC00ZGJkLWFkZjctMjE1MDg0ZDI1MjZj&x-client-SKU=ID_NET461&x-client-ver=5.3.0.0',
    authMechanism: 'oauth' as AuthMechanism,
    notes: 'Most POC effort is request packet and follow-up.',
  },
  {
    id: 'carrier-liberty',
    name: 'Liberty Mutual',
    adapterMode: 'PORTAL_GUIDED' as AdapterMode,
    supportsApi: false,
    requiresMfa: true,
    mfaMethod: 'totp',
    loginHint: 'liberty-admin',
    timeoutHours: 6,
    defaultTrustTier: 'TIER_2_CACHED_SESSION' as TrustTier,
    portalUrl: 'https://www.libertymutual.com',
    authMechanism: 'credentials' as AuthMechanism,
    notes: 'Portal-guided updates are stable; low automation depth.',
  },
  {
    id: 'carrier-statefarm',
    name: 'State Farm',
    adapterMode: 'MANUAL' as AdapterMode,
    supportsApi: false,
    requiresMfa: true,
    mfaMethod: 'email',
    loginHint: 'sfm-legacy',
    timeoutHours: 24,
    defaultTrustTier: 'TIER_1_ENTER_EVERY_TIME' as TrustTier,
    portalUrl: 'https://www.statefarm.com',
    authMechanism: 'phone_code' as AuthMechanism,
    notes: 'Manual tasks only until carrier process is re-homed.',
  },
  {
    id: 'carrier-hiscox',
    name: 'Hiscox',
    adapterMode: 'MANUAL' as AdapterMode,
    supportsApi: false,
    requiresMfa: false,
    mfaMethod: 'totp',
    loginHint: 'hiscox-legacy',
    timeoutHours: 12,
    defaultTrustTier: 'TIER_1_ENTER_EVERY_TIME' as TrustTier,
    portalUrl: 'https://www.hiscox.com',
    authMechanism: 'credentials' as AuthMechanism,
    notes: 'Long-tail exception path for this pilot.',
  },
  {
    id: 'carrier-berkshire',
    name: 'Berkshire Hathaway',
    adapterMode: 'PORTAL_GUIDED' as AdapterMode,
    supportsApi: false,
    requiresMfa: true,
    mfaMethod: 'push',
    loginHint: 'bhh-portal',
    timeoutHours: 8,
    defaultTrustTier: 'TIER_2_CACHED_SESSION' as TrustTier,
    portalUrl: 'https://www.berkshirehathaway.com',
    authMechanism: 'credentials' as AuthMechanism,
    notes: 'Needs guided admin workflow with periodic evidence capture.',
  },
  {
    id: 'carrier-chubb',
    name: 'Chubb',
    adapterMode: 'EMAIL_FORM' as AdapterMode,
    supportsApi: false,
    requiresMfa: true,
    mfaMethod: 'sms',
    loginHint: 'chubb-helpdesk',
    timeoutHours: 12,
    defaultTrustTier: 'TIER_1_ENTER_EVERY_TIME' as TrustTier,
    portalUrl: 'https://www.chubb.com',
    authMechanism: 'email_code' as AuthMechanism,
    notes: 'Email+form packet preferred for controlled onboarding.',
  },
  {
    id: 'carrier-endeavor',
    name: 'Endeavor Business Solutions',
    adapterMode: 'API_FEDERATED' as AdapterMode,
    supportsApi: true,
    requiresMfa: false,
    mfaMethod: 'totp',
    loginHint: 'endeavor-partners',
    timeoutHours: 6,
    defaultTrustTier: 'TIER_3_STORED_REGISTRY' as TrustTier,
    portalUrl: 'https://www.argolimited.com',
    authMechanism: 'sso_redirect' as AuthMechanism,
    notes: 'Good automation target among pilot shortlist.',
  },
  {
    id: 'carrier-axiom',
    name: 'Axiom Risk',
    adapterMode: 'EMAIL_FORM' as AdapterMode,
    supportsApi: false,
    requiresMfa: false,
    mfaMethod: 'email',
    loginHint: 'axiom-admin',
    timeoutHours: 12,
    defaultTrustTier: 'TIER_1_ENTER_EVERY_TIME' as TrustTier,
    portalUrl: 'https://www.axiomrisk.com',
    authMechanism: 'credentials' as AuthMechanism,
    notes: 'Legacy admin path; no API or direct SSO.',
  },
];

const users: BrokerUser[] = [
  {
    id: 'user-alex',
    name: 'Alex Metka',
    email: 'alex@bb.com',
    licenseNumber: 'FL-EX-1001',
    licenseState: 'FL',
    role: 'Broker Admin',
    employmentStatus: 'active',
    createdAt: seedTime,
  },
  {
    id: 'user-jordan',
    name: 'Jordan Cole',
    email: 'jcole@bb.com',
    licenseNumber: 'FL-EX-1002',
    licenseState: 'FL',
    role: 'Operations Producer',
    employmentStatus: 'active',
    createdAt: seedTime,
  },
  {
    id: 'user-mia',
    name: 'Mia Brooks',
    email: 'mrooks@bb.com',
    licenseNumber: 'FL-EX-1003',
    licenseState: 'FL',
    role: 'Marketing Specialist',
    employmentStatus: 'active',
    createdAt: seedTime,
  },
];

const defaultKnowledge: KnowledgeDoc[] = [
  {
    id: 'doc-cna-onboard',
    title: 'CNA: Onboard teammate + assign admin role',
    carrierId: 'carrier-cna',
    tags: ['onboarding', 'cna', 'admin'],
    body: 'Log into CNA carrier admin portal, navigate to Team settings, add user with name, email, license, then assign administrative and quote role if needed. Save and request case confirmation number.',
  },
  {
    id: 'doc-hartford-offboard',
    title: 'Hartford: deprovision flow',
    carrierId: 'carrier-hartford',
    tags: ['offboarding', 'deprovision', 'hartford'],
    body: 'From account admin page, disable user and remove quote and admin roles first, then revoke portal sessions if option exists.',
  },
  {
    id: 'doc-monoline-mfa',
    title: 'Monoline Work Comp: MFA expectation',
    carrierId: 'carrier-monoline',
    tags: ['mfa', 'troubleshooting'],
    body: 'Carrier sends a one-time code by text for new device logins. Broker keeps responsibility for final OTP entry; code cannot be replayed.',
  },
  {
    id: 'doc-travelers-role-map',
    title: 'Travelers role map',
    carrierId: 'carrier-travelers',
    tags: ['roles', 'role-mapping', 'travelers'],
    body: 'Map to Roles: View => "View Access"; Quote => "Underwriter Assistant"; Admin => "Portal Admin". Keep admin mapping centralized in the carrier package.',
  },
];

function makeSeedGrant(userId: string, carrierId: string, role: AccessRole): AccessGrant {
  return {
    id: uid('grant'),
    userId,
    carrierId,
    normalizedRole: role,
    carrierNativeRole: role,
    trustTier: pilotCarriers.find((carrier) => carrier.id === carrierId)?.defaultTrustTier || 'TIER_1_ENTER_EVERY_TIME',
    status: 'active',
  };
}

export function createSeedState(): AppState {
  const state: AppState = {
    users: [...users],
    carriers: [...pilotCarriers],
    accessGrants: [
      makeSeedGrant('user-alex', 'carrier-cna', 'ADMINISTRATIVE' as AccessRole),
      makeSeedGrant('user-alex', 'carrier-hartford', 'ADMINISTRATIVE' as AccessRole),
      makeSeedGrant('user-jordan', 'carrier-cna', 'QUOTING' as AccessRole),
      makeSeedGrant('user-mia', 'carrier-monoline', 'VIEW_ONLY' as AccessRole),
    ],
    tasks: [],
    requests: [],
    adminAssignments: [
      {
        id: uid('adminassign'),
        carrierId: 'carrier-cna',
        primaryAdminUserId: 'user-alex',
        backupAdminUserId: 'user-jordan',
      },
      {
        id: uid('adminassign'),
        carrierId: 'carrier-hartford',
        primaryAdminUserId: 'user-alex',
      },
      {
        id: uid('adminassign'),
        carrierId: 'carrier-travelers',
        primaryAdminUserId: 'user-jordan',
        backupAdminUserId: 'user-mia',
      },
      {
        id: uid('adminassign'),
        carrierId: 'carrier-monoline',
        primaryAdminUserId: 'user-alex',
      },
      {
        id: uid('adminassign'),
        carrierId: 'carrier-liberty',
        primaryAdminUserId: 'user-jordan',
        backupAdminUserId: 'user-alex',
      },
    ],
    vault: {},
    sessions: {},
    audits: [
      {
        id: uid('audit'),
        at: seedTime,
        actorEmail: 'system@local',
        action: 'seed.initialized',
        details: 'Seeded POC state with 12 carriers, 3 seeded users, and existing app continuity references.',
      },
    ],
    knowledge: [...defaultKnowledge],
  };
  return state;
}
